export default {
    list: {
        user: 'list-user',
        resident: 'list-resident',
        pinboard: 'list-pinboard',
        listing: 'list-listing',
        request: 'list-request',
        audit: 'list-audit',
        building: 'list-building',
        address: 'list-address',
        unit: 'list-unit',
        propertyManager: 'list-property_manager',
        quarter: 'list-quarter',
        template: 'list-template',
        provider: 'list-provider',
        requestCategory: 'list-service_request_category',
        audit: 'list-audit'
    },
    view: {
        user: 'view-user',
        userSetting: 'view-user_setting',
        resident: 'view-resident',
        pinboard: 'view-pinboard',
        listing: 'view-listing',
        provider: 'view-provider',
        building: 'view-building',
        address: 'view-address',
        unit: 'view-unit',
        propertyManager: 'view-property_manager',
        quarter: 'view-quarter',
        settings: 'view-settings',
        template: 'view-template',
        requestCategory: 'view-service_request_category'
    },
    create: {
        comment: 'add-comment',
        pinboard: 'add-pinboard',
        user: 'add-user',
        resident: 'add-resident',
        pinboardToAnyLocation: 'add-located-pinboard',
        listing: 'add-listing',
        provider: 'add-provider',
        residentRequest: 'add-request_resident',
        serviceRequest: 'add-request_service',
        request: 'add-request',
        building: 'add-building',
        address: 'add-address',
        unit: 'add-unit',
        propertyManager: 'add-property_manager',
        quarter: 'add-quarter',
        template: 'add-template',
        requestCategory: 'add-service_request_category'
    },
    update: {
        requestResident: 'edit-request_resident',
        user: 'edit-user',
        userSettings: 'edit-user_setting',
        resident: 'edit-resident',
        comment: 'edit-comment',
        pinboard: 'edit-pinboard',
        listing: 'edit-listing',
        provider: 'edit-provider',
        request: 'edit-request',
        residentRequest: 'edit-request_resident',
        serviceRequest: 'edit-request_service',
        building: 'edit-building',
        address: 'edit-address',
        unit: 'edit-unit',
        propertyManager: 'edit-property_manager',
        quarter: 'edit-quarter',
        settings: 'edit-settings',
        template: 'edit-template',
        requestCategory: 'edit-service_request_category'
    },
    delete: {
        user: 'delete-user',
        resident: 'delete-resident',
        pinboard: 'delete-pinboard',
        listing: 'delete-listing',
        provider: 'delete-provider',
        request: 'delete-request',
        building: 'delete-building',
        address: 'delete-address',
        unit: 'delete-unit',
        propertyManager: 'delete-property_manager',
        quarter: 'delete-quarter',
        template: 'delete-template',
        requestCategory: 'delete-service_request_category'
    },
    publish: {
        pinboard: 'publish-pinboard',
        listing: 'publish-listing'
    },
    pin: {
        pinboard: 'pin-pinboard'
    },
    assign: {
        provider: 'assign-provider',
        request: 'assign-request',
        manager: 'assign-property_manager'
    }
}