<?php

namespace App\Http\Requests\API\Quarter;

use App\Http\Requests\BaseRequest;

class EmailReceptionistRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return $this->user()->hasRole(['administrator', 'manager']);
    }

    public function rules()
    {
        // @TODO validate
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}
