<?php

namespace App\Repositories;

use App\Models\AuditableModel;
use App\Models\Model;
use App\Models\Relation;
use App\Models\Resident;
use App\Models\Unit;
use App\Traits\SaveMediaUploads;
use Illuminate\Support\Facades\App;

/**
 * Class RelationRepository
 * @package App\Repositories
 */
class RelationRepository extends BaseRepository
{
    use  SaveMediaUploads;


    /**
     * @var array
     */
    protected $fieldSearchable = [
        'relation_format' => 'like',
    ];

    /**
     * Configure the Model
     **/
    public function model()
    {
        return Relation::class;
    }

    /**
     * @param array $attributes
     * @return Relation|Model|mixed
     * @throws \OwenIt\Auditing\Exceptions\AuditingException
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function create(array $attributes)
    {
        \DB::beginTransaction();

        $attributes = $this->fixBuildingData($attributes);
        /**
         * @var Relation $model
         */
        $model = parent::create($attributes);

        if (empty($model))  {
            \DB::rollBack();
            return $model;
        }

        $model = $this->saveMediaUploads($model, $attributes);
        /**
         * @var $pinboardRepository PinboardRepository
         */
        $pinboardRepository = App::make(PinboardRepository::class);
        $pinboardRepository->newResidentRelationPinboard($model);
        $this->setAsResidentDefaultRelationIfNeed($model);
        \DB::commit();

        return $model;
    }

    /**
     * @param $relation
     * @return mixed
     * @throws \OwenIt\Auditing\Exceptions\AuditingException
     */
    protected function setAsResidentDefaultRelationIfNeed($relation)
    {
        if ($relation->status != Relation::StatusActive) {
            return $relation;
        }

        // save default_relation_id if need
        $relation->load('resident:id,default_relation_id');
        $resident = $relation->resident;

        if (! ($resident && is_null($resident->default_relation_id))) {
            return $relation;
        }
        
        Resident::disableAuditing();
        $resident->update(['default_relation_id' => $relation->id]);
        Resident::enableAuditing();
        (new AuditableModel())->newSystemAudit(
            'resident',
            $resident,
            AuditableModel::EventUpdated,
            true,
            [],
            true
        );

        return $relation;
    }

    /**
     * @param $unit
     * @param $residentId
     * @return Relation|Model|mixed
     * @throws \OwenIt\Auditing\Exceptions\AuditingException
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function newRelationForUnit($unit, $residentId)
    {
        $attr = [
            // @TODO other attributes
            'start_date' => now(),
            'unit_id' => $unit->id,
            'resident_id' => $residentId
        ];
        return  $this->create($attr);
    }

    /**
     * @param array $attributes
     * @param $id
     * @return mixed
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function update(array $attributes, $id)
    {
        $model = $this->model->findOrFail($id);
        return $this->updateExisting($model, $attributes);
    }

    /**
     * @param Model $model
     * @param $attributes
     * @return mixed
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function updateExisting(Model $model, $attributes)
    {
        $attributes = $this->fixBuildingData($attributes);
        $model =  parent::updateExisting($model, $attributes); // TODO: Change the autogenerated stub
        if ($model)  {
            $model = $this->saveMediaUploads($model, $attributes);
        }
        return $model;
    }

    /**
     * @param $attributes
     * @return mixed
     */
    public function fixBuildingData($attributes)
    {
        if (isset($attributes['unit_id'])) {
            $unit = Unit::with('building')->find($attributes['unit_id']);
            if ($unit) {
                $attributes['building_id'] = $unit->building_id;
                $attributes['unit_id'] = $unit->id;
            }
        }
        return $attributes;
    }
}
